(Tue Nov 19 16:02:08 2019)(-0.150291 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/pyscannerbit/ScannerBit/lib/libscanner_diver_1.0.0.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-0ai_8_ii/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(-0.150269 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/pyscannerbit/ScannerBit/lib/libscanner_diver_1.0.2.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-0ai_8_ii/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(-0.12924 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/pyscannerbit/ScannerBit/lib/libscanner_great.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-0ai_8_ii/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(-0.109244 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/pyscannerbit/ScannerBit/lib/libscanner_multinest_3.10.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-0ai_8_ii/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0169288 [s])[Default,Utilities]:
Random number engine mt19937_64 (default) selected with seed 1861036279.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0181905 [s])[Default,Printers][Info]:
Running shell command: rm -f pyscannerbit_run_data/toy_mcmc_scan/samples//results.hdf5
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0278916 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Plugin name is not defined under the "scanners" tag.  using the tag "badass" as the plugin name.

Raised at: line 625 in function void Gambit::Scanner::Plugins::pluginInfo::iniFile(const Gambit::Options&) of /tmp/pip-req-build-0ai_8_ii/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0281549 [s])[Default,Core]:
Starting scan.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0294041 [s])[Default,Printers][Info]:
Assigned printer ID '0' to output quantity with label 'LogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.029464 [s])[Default,Printers][Info]:
Assigned printer ID '1' to output quantity with label 'pointID'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.029509 [s])[Default,Printers][Info]:
Assigned printer ID '2' to output quantity with label 'MPIrank'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0307417 [s])[Default,Printers][Info]:
Assigned printer ID '3' to output quantity with label 'default::z'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0308429 [s])[Default,Printers][Info]:
Assigned printer ID '4' to output quantity with label 'default::x'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0309151 [s])[Default,Printers][Info]:
Assigned printer ID '5' to output quantity with label 'default::y'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.0312616 [s])[Default,Printers][Info]:
Assigned printer ID '6' to output quantity with label 'unitCubeParameters'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.033207 [s])[Default,Printers][Info]:
Assigned printer ID '7' to output quantity with label 'mult'
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.348453 [s])[Default]:
Synchronised buffers flushed for rank 0 printers. Waiting for all processes to flush their sync data before we try to write the RA data.
--<>--<>--<>--<>--<>--<>--<>--
(Tue Nov 19 16:02:08 2019)(0.350066 [s])[Default]:
GAMBIT run completed successfully.
--<>--<>--<>--<>--<>--<>--<>--
